### ISSUE TITLE
Classic Era spits errors

### ISSUE THREAD

**Issue by k9dog-gmail** [cdmichaelb/Outfitter#140]
Classic Era is 1.14.3. This addon claims to be Classic Era compatible. The errors seem to indicate otherwise. I know some errors might be expected due to people requesting Wrath, but would be nice to know status. I'll try downloading Wrath version and see if file lave just is wrongly indicating.

**Comment by Dragotex** [comment]
same problem for me - can you please fix it - this addon is so great and works so perfect with adi bags!!!!

**Comment by GovtGeek** [comment]
I don't currently have a classic era character, but I'll see what I can do. If nothing else, you should be able to use a previous version.

**Comment by DeTosc** [comment]
AFAIK, Blizzard changed the Lua API in 1.14.x (Era) to ... Shadowlands(?), introducing the infamous "Backdrop" errors to Era:

`27x ...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua:165: attempt to call method 'SetBackdrop' (a nil value)`

The good news is: The BCC version Outfitter-2.0.64.TBC seems to work fine for me.

**Comment by GovtGeek** [comment]
I created a new character to test in Classic. There were issues with the some namespace changes (C_Container being a major one). I have a fix I'm testing and hopefully should be available soon.

**Comment by GovtGeek** [comment]
Can you test out my draft release from my fork?
https://github.com/GovtGeek/Outfitter/releases/tag/3.0.4.6

**Comment by DeTosc** [comment]
I'am afraid that something went wrong and you rereleased the assets of the (not working) version 3.0.4 from 25 january 2023.
Look:
5x Interface\AddOns\Outfitter\OutfitterInventory.lua:845: attempt to index global 'C_Container' (a nil value)
[string "@Interface\AddOns\Outfitter\OutfitterInventory.lua"]:845: in function `Synchronize'
[string "@Interface\AddOns\Outfitter\OutfitterInventory.lua"]:760: in function `GetInventoryCache'
[string "@Interface\AddOns\Outfitter\Outfitter-3.0.4.lua"]:4018: in function `GetNewItemsOutfit'
[string "@Interface\AddOns\Outfitter\OutfitterEquipment.lua"]:991: in function `RestoreSavedStack'
[string "@Interface\AddOns\Outfitter\OutfitterEquipment.lua"]:969: in function `Initialize'
[string "@Interface\AddOns\Outfitter\Outfitter-3.0.4.lua"]:4778: in function `Function'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:242: in function `OnUpdate2'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:178: in function `OnUpdate'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:20: in function <...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20>

**Comment by GovtGeek** [comment]
Was that on login or did you do something specific?

**Comment by DeTosc** [comment]
I am using the BugGrabber/Bugsack Addons, which intercept&show all the Lua errors. And this shows up right after login.
Please check the assets attached to your release, these dates seems wrong to me:
![image](https://user-images.githubusercontent.com/23533666/232894016-6dbfc132-eb15-4b0d-9e98-815b005bf97a.png)

**Comment by GovtGeek** [comment]
I have a new release package up. Looks like I didn't package up the branch like I thought.

**Comment by DeTosc** [comment]
I confirm: No Lua errors on login and switching gear while riding works fine. It seems that we have a winner :)

**Comment by Dragotex** [comment]
Now i get errors with ADI bags when i activate the latest Outfitter, now lua error with deactivated outfitter:

Message: Interface\AddOns\AdiBags\core\Utility.lua:465: attempt to call field 'GetContainerItemQuestInfo' (a nil value)
Time: Wed Apr 19 03:33:38 2023
Count: 74
Stack: Interface\AddOns\AdiBags\core\Utility.lua:465: attempt to call field 'GetContainerItemQuestInfo' (a nil value)
[string "=[C]"]: in function `GetContainerItemQuestInfo'
[string "@Interface\AddOns\AdiBags\core\Utility.lua"]:465: in function `GetContainerItemQuestInfo'
[string "@Interface\AddOns\AdiBags\widgets\ItemButton.lua"]:333: in function `UpdateIcon'
[string "@Interface\AddOns\AdiBags\widgets\ItemButton.lua"]:344: in function `Update'
[string "@Interface\AddOns\AdiBags\widgets\ItemButton.lua"]:319: in function `FullUpdate'
[string "@Interface\AddOns\AdiBags\widgets\ItemButton.lua"]:276: in function <Interface\AddOns\AdiBags\widgets\ItemButton.lua:264>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:1093: in function `PrepareSections'
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:1215: in function `FullUpdate'
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:643: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:629>
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\core\Utility.lua"]:106: in function <Interface\AddOns\AdiBags\core\Utility.lua:98>
[string "@Interface\AddOns\AdiBags\widgets\LayeredRegion.lua"]:119: in function <Interface\AddOns\AdiBags\widgets\LayeredRegion.lua:108>

**Comment by GovtGeek** [comment]
That looks to be an issue with AdiBags not fixing the GetContainerItemQuestInfo call to a C_Container.GetContainerItemQuestInfo call. The change I made took out a bunch of C_Container fixes for things Outfitter didn't use.

**Comment by GovtGeek** [comment]
I took another look at the code. The current iteration of my fix ends up being global and affects other addons, instead of local to Outfitter as intended.

I'll work on trying to get it localized so it won't affect other addons.

**Comment by GovtGeek** [comment]
I worked through the AdiBags call and realized it even has a comment where the error happens:
> 	-- This function isn't present on classic-era in any form

This is why it's failing. I still needed to fix my scoping issue, but AdiBags still needs to do some checking that the function exists before trying to use it.

**Comment by GovtGeek** [comment]
@DeTosc Can you try the newer prerelease?
https://github.com/GovtGeek/Outfitter/releases/tag/3.0.4.6.2

@Dragotex  I know AdiBags doesn't work with the fix I'm linking, but it should be better overall. To temporarily fix AdiBags, try adding this in Utility.lua at line 463:
```
	_, _, _, toc = GetBuildInfo()
	if toc == 11403 then return nil, nil, nil end
```

**Comment by DeTosc** [comment]
https://github.com/GovtGeek/Outfitter/releases/tag/3.0.4.6.2 seems to work fine for me.

**Comment by Dragotex** [comment]
@GovtGeek thx for your help - seems workaround does its job - no lua errors in the last 3 hours

**Comment by Shamatix** [comment]
> @Dragotex I know AdiBags doesn't work with the fix I'm linking, but it should be better overall. To temporarily fix AdiBags, try adding this in Utility.lua at line 463:
> 
> ```
> 	_, _, _, toc = GetBuildInfo()
> 	if toc == 11403 then return nil, nil, nil end
> ```

Adding the line at 463 in Adibags solved the issue :)

**Comment by GovtGeek** [comment]
@DeTosc I moved some stuff around under the covers in a new release. Can you try it out to make sure I didn't break something else?
https://github.com/GovtGeek/Outfitter/releases/tag/3.0.4.6.4

@Dragotex @Shamatix Glad I could help. I posted the fix on the AdiBags issue too.

**Comment by DeTosc** [comment]
Hi, sorry for the late reply, well ... it seems that you released older, broken stuff from 25 january 
![image](https://user-images.githubusercontent.com/23533666/235263357-33426390-bebd-44f5-86e5-c623178a867e.png)

**Comment by GovtGeek** [comment]
> Hi, sorry for the late reply, well ... it seems that you released older, broken stuff from 25 january ![image](https://user-images.githubusercontent.com/23533666/235263357-33426390-bebd-44f5-86e5-c623178a867e.png)

Can you let me know what errors you got? I'm going back and forth between some branches and want to make sure I see the same things you do.

**Comment by DeTosc** [comment]
Well, first of all, outfitter is not considering the settings. I turn off the minimap button, with this version the button appears and clicking on it shows this weird cross:
![image](https://user-images.githubusercontent.com/23533666/235298680-25d2487a-7a30-4be6-a27b-0dec41f28d69.png)

The Frame besides the char panel is empty:
![image](https://user-images.githubusercontent.com/23533666/235298704-01ce40de-8bf8-4e28-852e-0b36069cfc67.png)

And this is the lua error messages I got from BugSack:

2x Interface\AddOns\Outfitter\OutfitterInventory.lua:845: attempt to index global 'C_Container' (a nil value)
[string "@Interface\AddOns\Outfitter\OutfitterInventory.lua"]:845: in function `Synchronize'
[string "@Interface\AddOns\Outfitter\OutfitterInventory.lua"]:760: in function `GetInventoryCache'
[string "@Interface\AddOns\Outfitter\Outfitter-3.0.4.lua"]:4018: in function `GetNewItemsOutfit'
[string "@Interface\AddOns\Outfitter\OutfitterEquipment.lua"]:991: in function `RestoreSavedStack'
[string "@Interface\AddOns\Outfitter\OutfitterEquipment.lua"]:969: in function `Initialize'
[string "@Interface\AddOns\Outfitter\Outfitter-3.0.4.lua"]:4778: in function `Function'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:242: in function `OnUpdate2'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:178: in function `OnUpdate'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:20: in function <...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20>

Locals:
self = <table> {
 FindItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1001
 ItemsByCode = <table> {
 }
 InventorySlotContainsItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1333
 InventoryItems = <table> {
 }
 InheritOver = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:128
 FindAllItems = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1120
 Synchronize = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:799
 ItemsBySlot = <table> {
 }
 GetMissingItems = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1178
 SwapLocationWithInventorySlot = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:965
 inherit = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:149
 GetBoEItems = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1231
 RemoveItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:911
 FindItemInfoByCode = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:977
 FindItemIndex = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1015
 FindItemInfoBySlot = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:989
 SwapBagSlotWithInventorySlot = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:973
 SwapLocations = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:952
 FlushBag = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1140
 inheritOver = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:128
 FlushInventory = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1151
 CompiledUnusedItemsList = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1190
 FirstBagIndex = 0
 NumBags = 0
 Flush = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:788
 BagItems = <table> {
 }
 AddItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:869
 ResetIgnoreItemFlags = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1170
 ItemsAreSame = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1257
 Inherit = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:149
 NeedsUpdate = true
 FindItemOrAlt = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1091
 Construct = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:775
 FindAllItemsOrAlt = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1109
}
vNumBags = 4
vFirstBagIndex = 0
(for index) = 0
(for limit) = 4
(for step) = 1
vBagIndex = 0
vBagItems = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
 JewelCode4 = 0
 Gem2 = ""
 UpgradeID = 0
 Code = 10725
 Gem1 = ""
 SlotName = "Trinket1Slot"
 BonusIDs = "::"
 UpgradeTypeID = 0
 EnchantCode = 0
 Gem4 = ""
 Level = 46
 Gem3 = ""
 Quality = 1
 InstanceDifficultyID = 0
 Type = "Trade Goods"
 InvType = "INVTYPE_TRINKET"
 Link = "|cffffffff|Hitem:10725::::::::52:::::::::|h[Gnomish Battle Chicken]|h|r"
 SubCode = 0
 ItemSlotName = "Trinket0Slot"
 SubType = "Devices"
 JewelCode2 = 0
 JewelCode1 = 0
 Texture = 135996
 Count = 1
 JewelCode3 = 0
 Location = <table> {
 }
 MinLevel = 0
 UniqueID = 0
 Name = "Gnomish Battle Chicken"
}
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
(*temporary) = <table> {
 ChestSlot = <table> {
 }
 HandsSlot = <table> {
 }
 WristSlot = <table> {
 }
 Trinket1Slot = <table> {
 }
 ShoulderSlot = <table> {
 }
 Trinket0Slot = <table> {
 }
 MainHandSlot = <table> {
 }
 Finger0Slot = <table> {
 }
 NeckSlot = <table> {
 }
 BackSlot = <table> {
 }
 FeetSlot = <table> {
 }
 RangedSlot = <table> {
 }
 LegsSlot = <table> {
 }
 WaistSlot = <table> {
 }
 HeadSlot = <table> {
 }
 Finger1Slot = <table> {
 }
}
(*temporary) 

Edit: After creating a new outfit, the saved outfits appear.

The outfits with automation fail to find their items like deep diving helmet or the carrot on a stick.
Trying to create more outfits result in a big delay and more lua erros:

9x Interface\AddOns\Outfitter\OutfitterInventory.lua:845: attempt to index global 'C_Container' (a nil value)
[string "@Interface\AddOns\Outfitter\OutfitterInventory.lua"]:845: in function `Synchronize'
[string "@Interface\AddOns\Outfitter\OutfitterInventory.lua"]:760: in function `GetInventoryCache'
[string "@Interface\AddOns\Outfitter\Outfitter-3.0.4.lua"]:4018: in function `GetNewItemsOutfit'
[string "@Interface\AddOns\Outfitter\OutfitterEquipment.lua"]:991: in function `RestoreSavedStack'
[string "@Interface\AddOns\Outfitter\OutfitterEquipment.lua"]:969: in function `Initialize'
[string "@Interface\AddOns\Outfitter\Outfitter-3.0.4.lua"]:4778: in function `Function'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:242: in function `OnUpdate2'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:178: in function `OnUpdate'
[string "@Interface\AddOns\Outfitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua"]:20: in function <...fitter\Libraries/MC2SchedulerLib/MC2SchedulerLib.lua:20>

Locals:
self = <table> {
 FindItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1001
 ItemsByCode = <table> {
 }
 InventorySlotContainsItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1333
 InventoryItems = <table> {
 }
 InheritOver = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:128
 FindAllItems = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1120
 Synchronize = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:799
 ItemsBySlot = <table> {
 }
 GetMissingItems = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1178
 SwapLocationWithInventorySlot = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:965
 inherit = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:149
 GetBoEItems = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1231
 RemoveItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:911
 FindItemInfoByCode = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:977
 FindItemIndex = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1015
 FindItemInfoBySlot = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:989
 SwapBagSlotWithInventorySlot = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:973
 SwapLocations = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:952
 FlushBag = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1140
 inheritOver = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:128
 FlushInventory = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1151
 CompiledUnusedItemsList = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1190
 FirstBagIndex = 0
 NumBags = 0
 Flush = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:788
 BagItems = <table> {
 }
 AddItem = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:869
 ResetIgnoreItemFlags = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1170
 ItemsAreSame = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1257
 Inherit = <function> defined @Interface\AddOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:149
 NeedsUpdate = true
 FindItemOrAlt = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1091
 Construct = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:775
 FindAllItemsOrAlt = <function> defined @Interface\AddOns\Outfitter\OutfitterInventory.lua:1109
}
vNumBags = 4
vFirstBagIndex = 0
(for index) = 0
(for limit) = 4
(for step) = 1
vBagIndex = 0
vBagItems = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
 JewelCode4 = 0
 Gem2 = ""
 UpgradeID = 0
 Code = 10725
 Gem1 = ""
 SlotName = "Trinket1Slot"
 BonusIDs = "::"
 UpgradeTypeID = 0
 EnchantCode = 0
 Gem4 = ""
 Level = 46
 Gem3 = ""
 Quality = 1
 InstanceDifficultyID = 0
 Type = "Trade Goods"
 InvType = "INVTYPE_TRINKET"
 Link = "|cffffffff|Hitem:10725::::::::52:::::::::|h[Gnomish Battle Chicken]|h|r"
 SubCode = 0
 ItemSlotName = "Trinket0Slot"
 SubType = "Devices"
 JewelCode2 = 0
 JewelCode1 = 0
 Texture = 135996
 Count = 1
 JewelCode3 = 0
 Location = <table> {
 }
 MinLevel = 0
 UniqueID = 0
 Name = "Gnomish Battle Chicken"
}
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
(*temporary) = <table> {
 ChestSlot = <table> {
 }
 HandsSlot = <table> {
 }
 WristSlot = <table> {
 }
 Trinket1Slot = <table> {
 }
 ShoulderSlot = <table> {
 }
 Trinket0Slot = <table> {
 }
 MainHandSlot = <table> {
 }
 Finger0Slot = <table> {
 }
 NeckSlot = <table> {
 }
 BackSlot = <table> {
 }
 FeetSlot = <table> {
 }
 RangedSlot = <table> {
 }
 LegsSlot = <table> {
 }
 WaistSlot = <table> {
 }
 HeadSlot = <table> {
 }
 Finger1Slot = <table> {
 }
}
(*temporary)

**Comment by GovtGeek** [comment]
Thanks for the errors. I think I didn't get a clean version when switching. I'll make sure I get it updated soon.

**Comment by GovtGeek** [comment]
Looks like I had some issues creating the packages. Both the vanilla namespace fix and the equipment manager fix used the main branch instead of the respective correct branches.

@DeTosc Release 3.0.4.6.5 should work now (I made sure to make a clean directory and test this time). I really do appreciate the help making it right before I release it.
https://github.com/GovtGeek/Outfitter/releases/tag/3.0.4.6.5

**Comment by DeTosc** [comment]
No worries, I am glad to help. 
Release 3.0.4.6.5 looks fine for me. No Lua errors so far, switching outfits automaticaly works!

**Comment by Drockzoids** [comment]
Is there someone that could help me get this working?  I can't seem to figure it out and I need my Outfitter. :(  Thanks.

**Comment by GovtGeek** [comment]
@Drockzoids Which errors are you getting? Have you tried the release on my fork for 3.0.4.6.5?

**Comment by AzucarSalado** [comment]
I can confirm that this version is working for me woth Classic 1.14.3:

https://github.com/GovtGeek/Outfitter/releases/tag/3.0.4.6.4

I was having the same problem as [DeTosc] witth the other versions.

Just for info, version still shows as 3.0.4. It is strange because version in CourseForge says last version is 1.3.2:

![image](https://user-images.githubusercontent.com/63239138/236777450-63e81c32-e70d-4bdf-9158-24fe27549603.png)

https://www.curseforge.com/wow/addons/outfitter-classic
WoW Classic 1.3.2

Thanks.

**Comment by kanodiry** [comment]
> Looks like I had some issues creating the packages. Both the vanilla namespace fix and the equipment manager fix used the main branch instead of the respective correct branches.
> 
> @DeTosc Release 3.0.4.6.5 should work now (I made sure to make a clean directory and test this time). I really do appreciate the help making it right before I release it. https://github.com/GovtGeek/Outfitter/releases/tag/3.0.4.6.5

Works well, thank you for fork!

**Comment by wambuwulance** [comment]
Hello! I love your add-on and have been using it since the beginning of classic <3. I'm currently playing on classic era but I keep getting an issue - I can customize and set up "Birthday Suit" and one more outfit but im unable to make more than those 2. Any chance you know what I could do to fix it? 

Date: 2023-07-31 19:16:34
ID: 3
Error occured in: Global
Count: 1
Message: ...tter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua line 165:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=[tsm error check]"]:1: in main chunk
   [string "=(tail call)"]: ?
   [string "=[C]"]: SetBackdrop()
   [string "@Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:165: SetDialogBackdrop()
   [string "@Outfitter\Libraries/MC2UIElementsLib/MC2UIElementsLib.lua"]:188: Construct()
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:145: inheritOver()
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:41: initObject()
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:15:
      ...dOns\Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua:6
   [string "=(tail call)"]: ?
   [string "@Outfitter\Libraries/MC2AddonLib/MC2AddonLib.lua"]:10: New()
   [string "@Outfitter\Outfitter.lua"]:3826: OpenNameOutfitDialog()
   [string "@Outfitter\Outfitter.lua"]:3839: CreateNewOutfit()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  ACP, v3.5.9
  AdvancedInterfaceOptions, v1.8.6
  Altoholic, v1.14.005
  Atlas, vv1.52.08
  AtlasClassicWoW, vv1.52.05
  AtlasDungeonLocs, vv1.52.04
  AtlasLootClassic, vv3.1.3
  AtlasLootClassicData, vv3.1.3
  AtlasLootClassicDungeonsAndRaids, vv3.1.3
  AtlasLootClassicMaps, vv1.0.0
  ATTClassic, v1.5.5
  Attune, v253
  AucAdvanced, v3.4.6844 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucScanData, v3.4.6804 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  Auctionator, v10.1.14
  BagBrother, v
  Bagnon, v10.1.4
  BagnonBoE, v2.0.65-Release
  BagnonGarbage, v2.0.52-Release
  BagnonItemInfo, v2.0.57-Release
  BagnonItemLevel, v2.0.77-Release
  BagSync, v19.19
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  BigDebuffs, vv11.30
  BigWigs, vv48.2-classic
  CharacterStatsClassic, v3.8.3
  ChatCopyPaste, v1.17
  ClassicAuraDurations, v3.4.0
  ClassicCastbars, vv1.6.3
  DataStore, v2023.05.04
  DataStoreAgenda, v2023.05.18
  DataStoreAuctions, v1.14.003
  DataStoreCharacters, v2023.05.03
  DataStoreContainers, v1.14.003
  DataStoreCrafts, v1.14.003
  DataStoreInventory, v1.14.003
  DataStoreMails, v2023.05.04
  DataStoreQuests, v1.14.003
  DataStoreReputations, v1.14.003
  DataStoreSpells, v2023.05.03
  DataStoreTalents, v1.14.003
  DBMCore, v845c443
  DBMSpellTimers, vr150
  DBMStatusBarTimers, v845c443
  DBMVPVEM, v0756aa0
  Decursive, v2.7.9.3
  Details, v#Details.20230731.11774.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsSunderCount, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6849 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  ExtendedCharacterStats, v3.1.1
  GatherMate2, v1.47-classic
  GatherMate2HideNodes, v30400 1r33
  GatherMate2Marker, v1.0.17
  Guidelime, v3.025
  Guidelimeahmp, v1.4
  GuidelimeBusteas160leveling, v2.3.0-Release
  GuidelimeFreezy3, v2.0
  GuidelimeMarkyMark, vv1.8
  GuidelimeMilksmugglerHC, v1
  GuidelimeSage, v1.0.4
  GuidelimeShiku, v0.001-Beta
  GuidelimeSummersisle170leveling, v0.6.3
  GuidelimeSunpower, v1.0.9-Release
  GuideLimeTUGsVanilla, v1.34
  HandyNotes, vv1.6.16
  HandyNotesCollection, v
  HandyNotesDraenor, v3.2
  HandyNotesDungeonLocationsClassic, v1.07a
  HandyNotesFlightMastersClassic, v1.12b
  HandyNotesGuild, v1.11
  HandyNotesNPCsClassic, v1.33b
  HandyNotesSummerFestival, v1.1
  HandyNotesTravelGuideClassic, vv3.5
  HandyNotesWorldMapButton, v100105.01-Release
  HHTD, v2.4.13
  HidingBar, vv1.14.42
  Informant, v3.4.6850 (SwimmingSeadragon)
  ItemRack, v3.75
  LeatrixMaps, v1.14.118
  LeatrixPlus, v1.14.118
  LFGBulletinBoard, v3.09
  Mapster, v1.10.8
  Misspelled, v1.9.9
  NovaInstanceTracker, v1.43
  NovaSpellRankChecker, v1.2
  NovaWorldBuffs, v2.53
  OmniBar, vv14.20
  OmniCC, v10.1.1
  Outfitter, v1.3.0
  Pawn, v2.8.3
  Plater, vPlater-v561.4-Classic
  PLG, v3.0
  Postal, vv4.0.0
  Prat30, v3.9.32
  Prat30Libraries, v
  Quartz, v3.7.6
  Questie, v8.8.3
  RareScanner, v1.14.3.2
  Scrap, v10.1.1
  SexyMap, vv10.1.3
  SilverDragon, vv2023.6.1
  SilverDragonOverlay, vv2023.6.1
  SilverDragonRangeExtender, vv2023.6.1
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  Spy, v1.2.3
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TacoTip, v0.4.3
  TargetHealth, v1.0.5
  TellMeWhen, v9.2.2
  ThreatClassic2, v2.48
  TomTom, vv3.5.1-release
  TradeSkillMaster, vv4.13.5
  TradeSkillMasterAppHelper, vv4.12.2
  TrinketMenu, v10.0.1
  VendorPrice, v1.6.7
  WeakAuras, v5.6.0
  WhatsTraining, v3.0.0
  WideQuestLog, v
  WideQuestLogLevels, v
  BlizRuntimeLib_enUS v1.14.3.11403 <none>
  (ck=f61)

**Comment by wambuwulance** [comment]
<img width="1512" alt="Screenshot 2023-07-21 at 2 52 52 PM" src="https://github.com/cdmichaelb/Outfitter/assets/141098739/34b84885-c585-46e6-8ec6-d35316cb5faf">

**Comment by wambuwulance** [comment]
<img width="1512" alt="Screenshot 2023-07-31 at 7 19 38 PM" src="https://github.com/cdmichaelb/Outfitter/assets/141098739/a0cf16b7-687f-4346-9bb6-da1a96cab95d">

**Comment by nezorflame** [comment]
See if https://github.com/cdmichaelb/Outfitter/pull/152 fixes it
